### ISSUE TITLE
Add user identity

### ISSUE THREAD

**Issue by andrii-i** [jupytercalpoly/jupyterlab-notifications#63]
#### Description
Currently, there is no user identity and therefore all notifications are delivered to everyone and it's not possible to send or deliver notifications to specific users. 

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Find identity solution to use (Quansight was working on something)
- [ ] Add identity to backend
- [ ] Add identity to frontend
- [ ] Update API specification

**Comment by hxmittal** [comment]
Pending work -

- The API specification has been updated and identity system has been updated to filter on both the frontend and the backend but still uses user entered username that is stored in the browser's localstorage. This should be updated to use JupyterLab's authentication mechanism.
